DROP DATABASE IF EXISTS crm;
CREATE DATABASE crm;
USE crm;

DROP TABLE IF EXISTS customer;

CREATE TABLE customer(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(10) NOT NULL,
	age INT, DEFAULT NULL
	height double(6,2) DEFAULT NULL
);