spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/driving_school?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

mybatis-plus:
  type-aliases-package: com.sl.pojo

logging:
  level:
    com.sl.mapper: debug